views:
  - title: Home New
    path: home-new
    icon: mdi:home-outline
    cards:
      - type: vertical-stack
        title: Living Room
        cards:
          - type: light
            entity: light.living_room
          - type: light
            entity: light.living_room_light_floor
      - type: vertical-stack
        title: Bedroom
        cards:
          - type: light
            entity: light.bedroom_light
          - type: light
            entity: light.bedside_light
          - type: light
            entity: light.elgato_key_light_808f
      - type: vertical-stack
        title: Hallway
        cards:
          - type: light
            entity: light.hallway
      - type: vertical-stack
        title: Kitchen
        cards:
          - type: light
            entity: light.kitchen_light
      - type: vertical-stack
        title: Bathroom
        cards:
          - type: light
            entity: light.bathroom_light
