views:
  - title: Home New
    path: home-new
    icon: mdi:home-outline
    type: sections
    max_columns: 2
    sections:
      - type: grid
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                name: I'm Home
                show_icon: false
                tap_action:
                  action: call-service
                  service: script.hello
              - type: button
                name: I'm Leaving
                show_icon: false
                tap_action:
                  action: call-service
                  service: script.goodbye
          - type: entities
            title: Living Room Lights
            icon: mdi:sofa
            show_header_toggle: false
            entities:
              - entity: light.living_room
              - entity: light.living_room_light_floor
          - type: entities
            title: Bedroom Lights
            icon: mdi:bed
            show_header_toggle: false
            entities:
              - entity: light.bedroom_light
              - entity: light.bedside_light
              - entity: light.elgato_key_light_808f
          - type: entities
            title: Hallway Lights
            icon: mdi:door
            show_header_toggle: false
            entities:
              - entity: light.hallway
          - type: entities
            title: Kitchen Lights
            icon: mdi:stove
            show_header_toggle: false
            entities:
              - entity: light.kitchen_light
          - type: entities
            title: Bathroom Lights
            icon: mdi:shower
            show_header_toggle: false
            entities:
              - entity: light.bathroom_light
      - type: grid
        cards:
          - type: media-control
            entity: media_player.living_room
          - type: media-control
            entity: media_player.apple_tv
          - type: media-control
            entity: media_player.bedroom
          - type: media-control
            entity: media_player.kitchen
          - type: media-control
            entity: media_player.bathroom
