views:
  - title: Home New
    path: home-new
    icon: mdi:home-outline
    type: sidebar
    cards:
      - type: grid
        columns: 2
        square: false
        cards:
          - type: button
            name: I'm Home
            icon: mdi:home-import-outline
            tap_action:
              action: call-service
              service: script.hello
          - type: button
            name: I'm Leaving
            icon: mdi:home-export-outline
            tap_action:
              action: call-service
              service: script.goodbye
      - type: grid
        columns: 3
        square: false
        cards:
          - type: entities
            title: Living Room
            icon: mdi:sofa
            show_header_toggle: false
            entities:
              - entity: light.living_room
              - entity: light.living_room_light_floor
              - entity: media_player.living_room
              - entity: media_player.apple_tv
          - type: entities
            title: Bedroom
            icon: mdi:bed
            show_header_toggle: false
            entities:
              - entity: light.bedroom_light
              - entity: light.bedside_light
              - entity: light.elgato_key_light_808f
              - entity: media_player.bedroom
          - type: entities
            title: Hallway
            icon: mdi:door
            show_header_toggle: false
            entities:
              - entity: light.hallway
          - type: entities
            title: Kitchen
            icon: mdi:stove
            show_header_toggle: false
            entities:
              - entity: light.kitchen_light
              - entity: media_player.kitchen
          - type: entities
            title: Bathroom
            icon: mdi:shower
            show_header_toggle: false
            entities:
              - entity: light.bathroom_light
              - entity: media_player.bathroom
